FROM python:3.11.5-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

#? Run with Uvicorn in development mode
CMD ["uvicorn","credsly.server:app","--host","0.0.0.0","--port","8080","--reload"]